package com.example.emp_project;

// Lombok annotations reduce boilerplate code (e.g., getters, setters, constructors).
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data // Generates getters, setters, toString(), equals(), and hashCode() automatically.
@NoArgsConstructor // Generates a no-argument constructor.
@AllArgsConstructor // Generates a constructor with all class fields as arguments.
public class Employee {

    // Fields representing employee details
    private Long id;       // Unique identifier for the employee
    private String name;   // Name of the employee
    private String phnNo;  // Phone number of the employee
    private String email;  // Email address of the employee

    // The following methods are automatically generated by Lombok:
    // - getId(), setId()
    // - getName(), setName()
    // - getPhnNo(), setPhnNo()
    // - getEmail(), setEmail()
    // - toString(), equals(), hashCode()
}


